import{a as v,i as n,S}from"./assets/vendor-u8rapaCG.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const q="44417625-4fee654a3e06908df7f1d6188",w="https://pixabay.com/api/";async function f(o,t=1,l=15){try{return(await v.get(w,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:l}})).data}catch(i){throw n.error({title:"Error",message:i.message,position:"topRight"}),i}}function p(o){const t=document.querySelector(".gallery"),l=o.map(({webformatURL:i,largeImageURL:e,tags:r,likes:c,views:y,comments:b,downloads:L})=>`
    <a href="${e}" class="gallery-item">
      <img src="${i}" alt="${r}" loading="lazy" />
      <div class="info">
        <p><b>Likes</b><br>${c}</p>
        <p><b>Views</b><br>${y}</p>
        <p><b>Comments</b><br>${b}</p>
        <p><b>Downloads</b><br>${L}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",l),new S(".gallery a").refresh()}function E(){document.querySelector(".gallery").innerHTML=""}const R=document.querySelector(".search-form"),P=document.querySelector(".search-input"),m=document.querySelector(".loader"),s=document.querySelector(".load-more");let d="",a=1,u=0;s.classList.add("hidden");function g(){m.classList.add("visible")}function h(){m.classList.remove("visible")}function $(){const t=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}R.addEventListener("submit",async o=>{if(o.preventDefault(),d=P.value.trim(),!d){n.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}a=1,E(),g();try{const t=await f(d,a);h(),u=Math.ceil(t.totalHits/t.hits.length),t.hits.length===0?(n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),s.classList.add("hidden")):(p(t.hits),a<u?s.classList.remove("hidden"):s.classList.add("hidden"))}catch(t){h(),n.error({title:"Error",message:t.message,position:"topRight"})}});s.addEventListener("click",async()=>{if(a>=u){n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),s.classList.add("hidden");return}a+=1,s.classList.add("hidden"),g();try{const o=await f(d,a);h(),o.hits.length>0&&(p(o.hits),$(),a<u?s.classList.remove("hidden"):(s.classList.add("hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})))}catch(o){h(),n.error({title:"Error",message:o.message,position:"topRight"})}});
//# sourceMappingURL=index.js.map
