import{a as L,i as a,S as v}from"./assets/vendor-u8rapaCG.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const S="44417625-4fee654a3e06908df7f1d6188",q="https://pixabay.com/api/";async function m(o,t=1,n=15){try{return(await L.get(q,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n}})).data}catch(s){throw a.error({title:"Error",message:s.message,position:"topRight"}),s}}function p(o){const t=document.querySelector(".gallery"),n=o.map(({webformatURL:s,largeImageURL:e,tags:r,likes:l,views:h,comments:y,downloads:b})=>`
    <a href="${e}" class="gallery-item">
      <img src="${s}" alt="${r}" loading="lazy" />
      <div class="info">
        <p><b>Likes</b><br>${l}</p>
        <p><b>Views</b><br>${h}</p>
        <p><b>Comments</b><br>${y}</p>
        <p><b>Downloads</b><br>${b}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",n),new v(".gallery a").refresh()}function w(){document.querySelector(".gallery").innerHTML=""}const E=document.querySelector(".search-form"),R=document.querySelector(".search-input"),f=document.querySelector(".loader"),i=document.querySelector(".load-more");let c="",d=1;i.classList.add("hidden");function g(){f.classList.add("visible")}function u(){f.classList.remove("visible")}function P(){const t=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}E.addEventListener("submit",async o=>{if(o.preventDefault(),c=R.value.trim(),!c){a.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}d=1,w(),g();try{const t=await m(c,d);u(),t.hits.length===0?(a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i.classList.add("hidden")):(p(t.hits),i.classList.remove("hidden"))}catch(t){u(),a.error({title:"Error",message:t.message,position:"topRight"})}});i.addEventListener("click",async()=>{d+=1,i.disabled=!0,g();try{const o=await m(c,d);u(),o.hits.length>0?(p(o.hits),P(),i.disabled=!1):(a.info({title:"Info",message:"No more images to load.",position:"topRight"}),i.classList.add("hidden"))}catch(o){u(),a.error({title:"Error",message:o.message,position:"topRight"}),i.disabled=!1}});
//# sourceMappingURL=index.js.map
